/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package laporan;

import apptracking.funct.koneksi;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author reki.pebriana
 */
public class lapTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form lapTransaksi
     */
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    JasperReport JasRep;
    JasperPrint JasPri;
    JasperDesign JasDes;

    public lapTransaksi() {
        initComponents();
        datatable();
        tanggal();
        lebarKolom();
        Object[] baris={"ID Karyawan","Nama","Jenis Kelamin","Jabatan","No.Telp","No.Ktp","Alamat"};
        tabmode = new DefaultTableModel(null,baris);
        Locale local = new Locale("id", "ID");
        Locale.setDefault(local);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lprint = new javax.swing.JLabel();
        lpreview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltrx = new javax.swing.JTable();
        ddari = new com.toedter.calendar.JDateChooser();
        dsampai = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcariKeyTyped(evt);
            }
        });

        jLabel1.setText("Pencarian");

        jLabel2.setText("Dari :");

        jLabel3.setText("Sampai :");

        lprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        lprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lprintMouseClicked(evt);
            }
        });

        lpreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/preview.png"))); // NOI18N
        lpreview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpreviewMouseClicked(evt);
            }
        });

        tbltrx.setBackground(new java.awt.Color(255, 255, 255));
        tbltrx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltrx);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddari, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dsampai, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(lpreview)
                        .addGap(27, 27, 27)
                        .addComponent(lprint)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ddari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dsampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lpreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lpreviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpreviewMouseClicked
        // TODO add your handling code here:

        datatable();
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggalAwal = String.valueOf(fm.format(ddari.getDate()));
        String tanggalAkhir = String.valueOf(fm.format(dsampai.getDate()));
        String sql = "select * from mst_trx where date(trxdate) between '" + tanggalAwal + "' and '" + tanggalAkhir + "'";
        System.out.println(tanggalAwal);
        System.out.println(tanggalAkhir);
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String faktur = hasil.getString("invoice");
                String tanggal = hasil.getString("trxdate");
                System.out.println(hasil.getString("trxdate"));
                String spk = hasil.getString("spk");
                String nmplg = hasil.getString("nmplg");
                String tujuan = hasil.getString("tujuan");
                String nmbrg = hasil.getString("nmbrg");
                String volume = hasil.getString("volume");
                String amount = hasil.getString("amount");
                String ppn = hasil.getString("ppn");
                String totamount = hasil.getString("totamount");

                String[] data = {"", faktur, tanggal, spk, nmplg, tujuan, nmbrg, volume, amount, ppn, totamount};
                tabmode.addRow(data);
                noTable();
                lebarKolom();
            }
        } catch (Exception e) {
        }
        lebarKolom();
        JOptionPane.showMessageDialog(null, "Selesai");
    }//GEN-LAST:event_lpreviewMouseClicked

    private void lprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lprintMouseClicked
        // TODO add your handling code here:

        try {
            Connection konn = new koneksi().connect();
            File file = new File("src/laporan/transaksi.jrxml");
            
            SimpleDateFormat fm1 = new SimpleDateFormat("yyyy-MM-dd");
            String tanggalAwal = String.valueOf(fm1.format(ddari.getDate()));
            SimpleDateFormat fm2 = new SimpleDateFormat("yyyy-MM-dd");
            String tanggalAkhir = String.valueOf(fm2.format(dsampai.getDate()));
            JasDes = JRXmlLoader.load(file);
            HashMap a =new HashMap();
            a.put("tglAwal", tanggalAwal);
            a.put("tglAkhir", tanggalAkhir);
            a.put("REPORT_DIR", getClass().getResource("/image/Logo.png").getPath().replaceAll("%20"," "));
            JasRep = JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, a, konn);
            //JasperViewer.viewReport(JasPri, false);
            JasperViewer jasperViewer = new JasperViewer(JasPri, false);
            jasperViewer.setExtendedState(jasperViewer.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
            jasperViewer.setVisible(true);
            //jasperViewer.setAlwaysOnTop(maximixed);
//            laporanBarangMasuk.this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal membuka Laporan", "Cetak laporan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lprintMouseClicked

    private void txtcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyTyped
        // TODO add your handling code here:
        String sqlPencarian = "select * from mst_trx where trxid like '%" + txtcari.getText() + "%' or invoice like '%" + txtcari.getText() + "%' or nmplg like '%" + txtcari.getText() + "%' or tujuan like '%" + txtcari.getText() + "%' or spk like '%" + txtcari.getText() + "%'";
        pencarian(sqlPencarian);
        lebarKolom();
    }//GEN-LAST:event_txtcariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ddari;
    private com.toedter.calendar.JDateChooser dsampai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lpreview;
    private javax.swing.JLabel lprint;
    private javax.swing.JTable tbltrx;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables

    public void noTable() {
        int Baris = tabmode.getRowCount();
        for (int a = 0; a < Baris; a++) {
            String nomor = String.valueOf(a + 1);
            tabmode.setValueAt(nomor + ".", a, 0);
        }
    }

    public void tanggal() {
        Date tgl = new Date();
        ddari.setDate(tgl);
        dsampai.setDate(tgl);
    }

    public void datatable() {

        Object[] Baris = {"No", "Faktur", "Tanggal", "No SPK", "Nama Pelanggan", "Tujuan", "Nama Barang", "Volum", "Harga", "PPN", "Total Harga"};
        tabmode = new DefaultTableModel(null, Baris);
        tbltrx.setModel(tabmode);
    }

    public void lebarKolom() {
        TableColumn column;
        tbltrx.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tbltrx.getColumnModel().getColumn(0);
        column.setPreferredWidth(40);
        column = tbltrx.getColumnModel().getColumn(1);
        column.setPreferredWidth(100);
        column = tbltrx.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
        column = tbltrx.getColumnModel().getColumn(3);
        column.setPreferredWidth(200);
        column = tbltrx.getColumnModel().getColumn(4);
        column.setPreferredWidth(200);
        column = tbltrx.getColumnModel().getColumn(5);
        column.setPreferredWidth(250);
        column = tbltrx.getColumnModel().getColumn(6);
        column.setPreferredWidth(100);
        column = tbltrx.getColumnModel().getColumn(7);
        column.setPreferredWidth(100);
        column = tbltrx.getColumnModel().getColumn(8);
        column.setPreferredWidth(150);
        column = tbltrx.getColumnModel().getColumn(9);
        column.setPreferredWidth(150);
        column = tbltrx.getColumnModel().getColumn(10);
        column.setPreferredWidth(150);

    }

    public void pencarian(String sql) {
        Object[] Baris = {"No", "Faktur", "Tanggal", "No SPK", "Nama Pelanggan", "Tujuan", "Nama Barang", "Volum", "Harga", "PPN", "Total Harga"};
        tabmode = new DefaultTableModel(null, Baris);
        tbltrx.setModel(tabmode);
        int brs = tbltrx.getRowCount();
        for (int i = 0; 1 < brs; i++) {
            tabmode.removeRow(1);
        }
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String faktur = hasil.getString("invoice");
                String tanggal = hasil.getString("trxdate");
                String spk = hasil.getString("spk");
                String nmplg = hasil.getString("nmplg");
                String tujuan = hasil.getString("tujuan");
                String nmbrg = hasil.getString("nmbrg");
                String volume = hasil.getString("volume");
                String amount = hasil.getString("amount");
                String ppn = hasil.getString("ppn");
                String totamount = hasil.getString("totamount");

                String[] data = {"", faktur, tanggal, spk, nmplg, tujuan, nmbrg, volume, amount, ppn, totamount};
                tabmode.addRow(data);
                noTable();
            }
        } catch (Exception e) {

        }
    }
}
